backend:
  repo: fessehaye/ABSmash-Docs
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

publish_mode: editorial_workflow

media_folder: "docs/.vuepress/public/upload"
public_folder: "/upload"

collections:
  - name: "guides"
    label: "Guides"
    folder: "docs/Guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "toing"
    label: "TOing"
    folder: "docs/TOing"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "meetings"
    label: "Meeting Minutes"
    folder: "docs/meetings"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "resources"
    label: "Resources"
    files:
      - label: "Home Page"
        name: "home"
        file: "docs/Resources/README.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
